### ISSUE TITLE
bom dia

### ISSUE THREAD

**Issue by ghost** [Kiirx/ProjectOrizonOS#10]
bom dia meu amigo, meu caro meu cupixa meu parceiro camarada, esse sistema operativo funcionaria no meu toca fitas de 1970, precisa ter suporte ao TRIM tb :(

**Comment by selkij** [comment]
Please speak in english

**Comment by ghost** [comment]
speak english é a minha rola

**Comment by selkij** [comment]
coo-coo crazy my friend

**Comment by asterd-og** [comment]
> speak english é a minha rola

tem suporte não "amigão", só suporta PC msm, e tmb, tenta tratar os outros com mais respeito 👍

**Comment by ghost** [comment]
legal, mas você sabe o que é sexo?
